---
title: "project"
output: html_document
date: "2023-05-01"
---

```{r}
# load libraries
library(cluster)
library(dplyr)
library(magrittr)
library(ggplot2)
library(plotly)
library(data.table)
library(ggbiplot)
library(tidyr)
library(cowplot)
library(data.table)
library(lubridate)
library("factoextra")
#library(caret)
library(ggbiplot)
library(cowplot)
library(lubridate)
```


```{r}
df <- read.csv("Amazon.csv")
df$Date <- as.Date(df$Date, format = "%m-%d-%Y")
df<-na.omit(df)
df<-subset(df,select=-c(Sales.Channel,currency,ship.country,Order.ID,Courier.Status,promotion.ids,Unnamed..22,SKU))

proc_df<-df
```


```{r}
# create mapping for unique values based on severity
status_mapping <- setNames(c(0, 2, 1, 6, 11, 7, 3, 8, 4, 10, 9, 12, 5), 
                           c("Cancelled", "Shipped - Delivered to Buyer", "Shipped",
                             "Shipped - Returned to Seller", "Shipped - Rejected by Buyer",
                             "Shipped - Lost in Transit", "Shipped - Out for Delivery",
                             "Shipped - Returning to Seller", "Shipped - Picked Up",
                             "Pending - Waiting for Pick Up", "Pending", "Shipped - Damaged",
                             "Shipping"))


proc_df$Status <- status_mapping[proc_df$Status]

unique_fulfillment <- unique(proc_df$Fulfilment)
fulfillment_mapping <- setNames(seq_along(unique_fulfillment) - 1, unique_fulfillment)
proc_df$Fulfilment <- fulfillment_mapping[proc_df$Fulfilment]

service_level_mapping <- c("Standard" = 1, "Expedited" = 2)
proc_df$ship.service.level <- service_level_mapping[proc_df$ship.service.level]

cat_mapping <- c("Set" = 1, "kurta" = 2, "Western Dress" = 3, "Top" = 4, "Ethnic Dress" = 5, "Bottom" = 6, "Saree" = 7, "Blouse" = 8, "Dupatta" = 9)
proc_df$Category <- cat_mapping[proc_df$Category]

size_mapping <- c("S" = 2, "XS" = 1, "M" = 3, "L" = 4, "XL" = 5, "XXL" = 6, "3XL" = 7, "4XL" = 8, "5XL" = 9, "6XL" = 10, "Free" = 11)
proc_df$Size <- size_mapping[proc_df$Size]

b2b_mapping <- c("False"=0,"True"=1)
proc_df$B2B <- b2b_mapping[proc_df$B2B]

unique_style <- unique(proc_df$Style)
style_mapping <- setNames(seq_along(unique_style) - 1, unique_style)
proc_df$Style <- style_mapping[proc_df$Style]


unique_asin <- unique(proc_df$ASIN)
asin_mapping <- setNames(seq_along(unique_asin) - 1, unique_asin)
proc_df$ASIN <- asin_mapping[proc_df$ASIN]

# map the "Fulfillment" column to numeric values
proc_df<-subset(proc_df,select=-c(ship.city,ship.state,fulfilled.by,Date))

```

```{r}
min_max_scale <- function(x) {
  (x - min(x)) / (max(x) - min(x))
}
proc_df[] <- lapply(proc_df, min_max_scale)
```

```{r}
predictors <- proc_df %>% select(-index)
pca_model <- prcomp(predictors, scale = T)
pca_model$rotation <- -1*pca_model$rotation
pca_model$x <- -1*pca_model$x
head(pca_model$rotation)
```

**Make a scree plot**
```{r}
#calculate total variance explained by each principal component
var_explained <- pca_model$sdev^2 / sum(pca_model$sdev^2)
percent_var <- 100*var_explained
par(mfrow = c(1, 2))
plot(percent_var, xlab = "Principal Component",
    ylab = "Proportion of Variance Explained",
    type = "b")
plot(cumsum(percent_var), xlab = "Principal Component",
    ylab = "Cumulative Proportion of Variance Explained",
     type = "b")

```



```{r}
proc_df_selected <- proc_df %>% 
  select(Fulfilment, ship.service.level, Style, Category, Status)

head(proc_df_selected)
```



```{r}
# Take a random sample of 10,000 rows from the PCA output
set.seed(123)
sample_rows <- sample(nrow(proc_df_selected), 10000)
sample <- proc_df_selected[sample_rows, ]


# Compute pairwise distances based on first three principal components
data_dist <- dist(sample)

# Perform hierarchical clustering using complete linkage
data_complete <- hclust(data_dist, method = "complete")

# Plot dendrogram
plot(data_complete, main = "Complete Linkage Dendrogram for data")
```


```{r}
set.seed(234)
fviz_nbclust(sample, kmeans, method = "wss",k.max=10, nstart=30, iter.max=30) +
  geom_vline(xintercept = 2, linetype = 2)+
  labs(subtitle = "Elbow method")

```
```{r}
kmeans_out_3 <- kmeans(sample, centers = 2, nstart = 25)
cluster_assignments_3 <- kmeans_out_3$cluster
plot(pca_model$x[,1], pca_model$x[,2], xlab = "PC1", ylab = "PC2", col = cluster_assignments_3)
```


